server:
  port: 8080

spring:
  application:
    name: reniec-service
  r2dbc:
    url: ${DATABASE_URL}
    # r2dbc:postgresql://ep-aged-wind-a5enixuk.us-east-2.aws.neon.tech/neondb?sslmode=require
    username: ${DATABASE_USER}
    # neondb_owner
    password: ${DATABASE_PASSWORD}
    # 4yAJol2zpRgk
  contentmoderator:
    token: ${TOKEN_API}
    # eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imp1bGlvLnF1aXNwZUB2YWxsZWdyYW5kZS5lZHUucGUifQ.6M-P2QMMvKFZEeMvTUXvkOooM02N_pWqt0OdlaYW3PM
